# Generated by Django 3.2.7 on 2021-09-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210911_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item_price',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
