# Generated by Django 3.2.7 on 2021-09-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210911_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_description',
            field=models.TextField(default='kuch bhi daal do bhai'),
            preserve_default=False,
        ),
    ]
