# Generated by Django 3.2.7 on 2021-10-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_item_item_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item_name',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shop_name',
            new_name='shop_id',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
