# Generated by Django 3.2.7 on 2021-10-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobile_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
