# Generated by Django 3.2.7 on 2021-10-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_order_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
